name: cybersecurity_zen_koans
description: "A new Flutter project."
publish_to: 'none'

version: 3.1.0+5

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.4
  sensors_plus: ^6.1.1
  url_launcher: ^6.3.1
  screenshot: ^3.0.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  http: ^1.3.0
  flutter_svg: ^2.0.17
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/koans.json
    - assets/ktech_logo_light.svg
    - assets/ktech_logo_dark.svg
